# Archivo en la raíz del proyecto
sonar.projectKey=yxdhii_api-productos
sonar.organization=yxdhii
sonar.host.url=https://sonarcloud.io
# Ruta estándar donde Maven guarda el reporte de JaCoCo
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml